---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: letsencrypt-bullseye64
    box: debian/bullseye64
  - name: letsencrypt-buster64
    box: debian/buster64
  - name: letsencrypt-centos7
    box: centos/7
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: true
