---
- name: Get URL of latest Lego
  ansible.builtin.uri:
    url: https://api.github.com/repos/go-acme/lego/releases/latest
    body_format: json
    return_content: true
    remote_src: false
  register: json_response

# - name: Debug json_response
#   debug:
#     msg: >-
#       {{
#         (json_response.json.assets | selectattr('browser_download_url', 'search', 'lego_' + (lego_v) + '_linux_amd64.tar.gz')
#         | list | first).browser_download_url
#       }}

- name: "Install {{ json_response.json.tag_name }}"
  ansible.builtin.unarchive:
    src: >-
      {{
        (json_response.json.assets | selectattr('browser_download_url', 'search', 'lego_' + (lego_v) + '_linux_amd64.tar.gz')
        | list | first).browser_download_url
      }}
    dest: /usr/bin/
    remote_src: true

- name: Create Letsencrypt directory
  ansible.builtin.file:
    path: '{{ item.src }}'
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - { src: /etc/letsencrypt/ }

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: lego_ssl.sh.j2
    dest: "{{ script_path }}"
    owner: root
    group: root
    mode: '0700'

- name: Issue a Letsencrypt certificate
  ansible.builtin.command:
    argv:
      - "{{ script_path }}"
      - run
