---
- name: Ensure systemd timesyncd
  tags:
    - systemd_timesyncd
    - systemd
    - timesyncd
  block:
    - name: Ensure systemd timesyncd environment facts are collected
      import_tasks: environment.yml
      # ansible.builtin.import_tasks: environment.yml
    - name: Ensure systemd timesyncd package
      import_tasks: package.yml
      # ansible.builtin.import_tasks: package.yml
    - name: Ensure systemd timesyncd timesyncd.conf
      import_tasks: timesyncd.conf.yml
      # ansible.builtin.import_tasks: timesyncd.conf.yml
    - name: Ensure systemd timesyncd systemd service
      import_tasks: systemd_service.yml
      # ansible.builtin.import_tasks: systemd_service.yml
