---
- name: Website deployment
  hosts: hosting
  gather_facts: true
  roles:
    - role: common
    - role: baseline
    - role: systemd_journald
    - role: systemd_timesyncd
    - role: node_exporter

  vars:
    docker_compose_version: '2.20.3'
    systemd_journald_systemmaxuse: "2G"
    node_exporter_version: 1.6.1 # https://github.com/prometheus/node_exporter/releases
    node_exporter_enabled_collectors:
      - systemd
      - textfile:
          directory: "{{ node_exporter_textfile_dir }}"
      - filesystem:
          ignored-mount-points: "^/(sys|proc|dev)($|/)"
          ignored-fs-types: "^(sys|proc|auto)fs$"
